local_costmap:
    local_costmap:
        ros__parameters:
            update_frequency: 5.0
            publish_frequency: 2.0
            global_frame: map
            robot_base_frame: livox
            rolling_window: true
            width: 8
            height: 8
            resolution: 0.05
            robot_radius: 0.11
            plugins: ["obstacle_layer", "inflation_layer"]
            obstacle_layer:
                plugin: "nav2_costmap_2d::ObstacleLayer"
                enabled: true
                observation_sources: scan1
                min_obstacle_height: -0.2
                max_obstacle_height: 1.5
                scan1:
                    topic: "/cloud_registered_body"
                    expected_update_rate: 0.0
                    max_obstacle_height: 1.5
                    min_obstacle_height: -0.2
                    clearing: true
                    marking: true
                    data_type: "PointCloud2"
                    raytrace_max_range: 10.0
                    raytrace_min_range: 0.1
                    obstacle_max_range: 10.0
                    obstacle_min_range: 0.1
            inflation_layer:
                plugin: "nav2_costmap_2d::InflationLayer"
                cost_scaling_factor: 5.0
                inflation_radius: 0.5
            always_send_full_costmap: true

global_costmap:
    global_costmap:
        ros__parameters:
            update_frequency: 2.0
            publish_frequency: 1.0
            global_frame: map
            robot_base_frame: livox
            rolling_window: true
            width: 12
            height: 12
            resolution: 0.05
            track_unknown_space: false
            footprint: "[ [0.28, 0.15], [-0.28, 0.15], [-0.28, -0.15], [0.28, -0.15] ]"
            plugins: ["obstacle_layer", "inflation_layer"]
            obstacle_layer:
                plugin: "nav2_costmap_2d::ObstacleLayer"
                enabled: true
                observation_sources: scan1
                min_obstacle_height: -0.2
                max_obstacle_height: 1.5
                scan1:
                    topic: "/cloud_registered_body"
                    expected_update_rate: 0.0
                    max_obstacle_height: 1.5
                    min_obstacle_height: -0.2
                    clearing: true
                    marking: true
                    data_type: "PointCloud2"
                    raytrace_max_range: 10.0
                    raytrace_min_range: 0.1
                    obstacle_max_range: 10.0
                    obstacle_min_range: 0.1
            inflation_layer:
                plugin: "nav2_costmap_2d::InflationLayer"
                cost_scaling_factor: 5.0
                inflation_radius: 0.8
            always_send_full_costmap: true
